[package]
name = "thea-executor"
version = "1.1.0"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-support = { default-features = false, workspace = true }
frame-system = { default-features = false, workspace = true }
sp-runtime = { default-features = false, workspace = true }
sp-std = { workspace = true, default-features = false }
polkadex-primitives = { workspace = true, default-features = false }
rust_decimal = { workspace = true, features = ["scale-codec"], default-features = false }
pallet-timestamp = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
thea-primitives = { path = "../../primitives/thea", default-features = false }
xcm = { workspace = true, default-features = false }

[dev-dependencies]
pallet-assets = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
sp-application-crypto = { workspace = true }
sp-keystore = { workspace = true }
thea = { path = "../thea" }

[features]
default = ["std"]
std = [
  "sp-application-crypto/std",
  "thea-primitives/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
  "sp-runtime/std",
  "sp-std/std",
  "polkadex-primitives/std",
  "rust_decimal/std",
  "pallet-timestamp/std",
  "frame-benchmarking?/std",
  "sp-core/std",
  "sp-io/std",
  "thea/std",
]

runtime-benchmarks = [
  "sp-runtime/runtime-benchmarks",
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
