[package]
name = "polkadex-client"
version = "0.1.0"
edition = "2021"

[dependencies]
sc-executor = { workspace = true }
node-polkadex-runtime = { path = "../runtime", version = "4.0.0" }
frame-benchmarking = { workspace = true }
bls-primitives = {path = "../primitives/bls-primitives"}
