[package]
name = "polkadex-client"
version = "1.1.0"
edition = "2021"

[dependencies]
sc-executor = { workspace = true }
node-polkadex-runtime = { path = "../runtime" }
frame-benchmarking = { workspace = true }
