
//! Autogenerated weights for `pdex_migration`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-09-26, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/polkadex-node
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet=pdex_migration
// --extrinsic=*
// --steps
// 50
// --repeat
// 20
// --output=benchout/pdex_migration.rs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for pdex_migration.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	// Storage: PDEXMigration Operational (r:0 w:1)
	fn set_migration_operational_status() -> Weight {
		(1_000_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PDEXMigration Relayers (r:0 w:1)
	fn set_relayer_status() -> Weight {
		(14_000_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PDEXMigration Operational (r:1 w:0)
	// Storage: PDEXMigration EthTxns (r:1 w:1)
	// Storage: PDEXMigration Relayers (r:1 w:0)
	// Storage: PDEXMigration MintableTokens (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: PDEXMigration LockedTokenHolders (r:0 w:1)
	fn mint() -> Weight {
		(70_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: PDEXMigration Operational (r:1 w:0)
	// Storage: PDEXMigration LockedTokenHolders (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	fn unlock() -> Weight {
		(30_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: PDEXMigration LockedTokenHolders (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: PDEXMigration MintableTokens (r:1 w:1)
	fn remove_minted_tokens() -> Weight {
		(56_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
}
