language: rust
os: linux
rust:
  - nightly-2020-09-28
branches:
  only:
    - master
before_script:
  - rustup target add wasm32-unknown-unknown --toolchain nightly-2020-09-28
script:
  - cargo test --verbose
