version: '3'
services:
  node_alice:
    image: polkadex-node
    container_name: alice
    command: >
      /Polkadex/target/release/polkadex-node --base-path /tmp/alice --chain local --alice --port 30333 --ws-port 9945 --rpc-port 9933 --node-key 0000000000000000000000000000000000000000000000000000000000000001 --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --validator
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9945:9944"
    volumes:
      - "polkadot-data-alice:/data"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  node_bob:
    image: polkadex-node
    container_name: bob
    command: >
      /Polkadex/target/release/polkadex-node --base-path /tmp/bob --chain local --bob --port 30334 --ws-port 9946 --rpc-port 9934 --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --validator --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
    ports:
      - "30334:30333"
      - "9934:9933"
      - "9946:9944"
    volumes:
      - "polkadot-data-bob:/data"
    links:
      - "node_alice:alice"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

volumes:
  polkadot-data-alice:
  polkadot-data-bob:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16