[package]
name = "pallet-rewards-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136" }
parity-scale-codec = { workspace = true, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }
sp-rpc = { workspace = true }
sp-blockchain = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
polkadex-primitives = { workspace = true }
pallet-rewards-runtime-api = { path = "runtime-api" }
serde_json = "1.0.96"