[package]
authors = ['Polkadex Authors']
description = 'Uniswap V2 Pallet'
edition = '2018'
homepage = 'https://polkadex.trade'
name = 'polkadex-uniswap'
version = '1.0.0'

[dependencies]
serde = { version="1.0.101", optional=true }
codec = { version="2.0.0", package="parity-scale-codec", default-features=false, features=["derive"] }

frame-support = { git="https://github.com/paritytech/substrate", default-features=false }
frame-system = { git="https://github.com/paritytech/substrate", default-features=false }
sp-io = { git="https://github.com/paritytech/substrate", default-features=false }
sp-core = { git="https://github.com/paritytech/substrate", default-features=false }
sp-std = { git="https://github.com/paritytech/substrate", default-features=false }
sp-runtime = { git="https://github.com/paritytech/substrate", default-features=false }
frame-benchmarking = { git="https://github.com/paritytech/substrate", default-features=false, optional=true }
max-encoded-len = { git="https://github.com/paritytech/substrate", default-features=false }
orml-traits = { git="https://github.com/Polkadex-Substrate/open-runtime-module-library.git", default-features=false }
polkadex-primitives = { git="https://github.com/Polkadex-Substrate/polkadex-primitives.git", branch='main', default-features=false }
pallet-balances = { git="https://github.com/paritytech/substrate", version="3.0.0", default-features=false }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "polkadex-primitives/std",
    "orml-tokens/std",
    "orml-currencies/std",
    "pallet-balances/std",
]
try-runtime = ["frame-support/try-runtime"]
