[package]
authors = ['Mambisi Zempare <mambisi@polkadex.trade>']
description = 'FRAME pallet for Token Faucet'
edition = '2018'
homepage = 'https://polkadex.trade'
name = 'token-faucet-pallet'
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
polkadex-primitives = { path = "../../primitives", default-features = false }
orml-traits = { git = "https://github.com/Polkadex-Substrate/open-runtime-module-library.git", default-features = false }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'orml-traits/std',
    'polkadex-primitives/std',
]
