[package]
authors = ['Mambisi Zempare <mambisi@polkadex.trade>']
description = 'FRAME pallet for Token Faucet'
edition = '2018'
homepage = 'https://polkadex.trade'
name = 'token-faucet-pallet'
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
parking_lot = '0.11'
sp-keystore = { version = '0.9', optional = true }
pallet-balances = { version = '3.0', default-features = false }
[dev-dependencies]
serde = { version = "1.0.119" }
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }


[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-keystore/std',
]
