[package]
name = "thea-staking"
version = "4.0.0-dev"
authors = ["Polkadex Authors <business@polkadex.trade>"]
edition = "2021"
license = "GNU GPL v3"
homepage = "https://polkadex.trade"
repository = "https://github.com/Polkadex-Substrate/Polkadex/"
description = "Staking functionality for Thea bridge"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = {workspace = true, default-features = false }
log = { workspace = true, default-features = false }
scale-info =  { workspace = true, default-features = false, features = ["derive"] }
frame-support = { default-features = false, workspace = true }
frame-system ={ default-features = false, workspace = true }
pallet-balances = { default-features = false, workspace = true }
polkadex-primitives = { workspace = true, default-features = false }
pallet-staking = { default-features = false, workspace = true }
sp-runtime = { default-features = false, workspace = true }
sp-std = { default-features = false, workspace = true }
sp-staking = { default-features = false, workspace = true }
sp-io = { default-features = false, workspace = true }
thea-primitives = { path = "../../thea-primitives", default-features = false }

[dev-dependencies]
frame-benchmarking = { workspace = true }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-balances/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-staking/std",
	"sp-io/std",
	"thea-primitives/std",
	"polkadex-primitives/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
