[package]
name = "rpc-assets"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.136" }
parity-scale-codec = { workspace = true, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
sp-rpc = { workspace = true }
sp-blockchain = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
polkadex-primitives = { workspace = true }
rpc-assets-runtime-api = { path = "runtime-api" }
