//! Autogenerated weights for `pallet_ocex_lmp`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-10-24, STEPS: `100`, REPEAT: `200`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-41-122`, CPU: `AMD EPYC 7571`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./polkadex-node
// benchmark
// pallet
// --pallet
// pallet-ocex-lmp
// --steps
// 100
// --repeat
// 200
// --extrinsic
// *
// --output
// ocex_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_ocex_lmp`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::OcexWeightInfo for WeightInfo<T> {
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::Accounts` (r:1 w:1)
	/// Proof: `OCEX::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[0, 50000]`.
	fn register_main_account(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3632`
		// Minimum execution time: 56_052_000 picoseconds.
		Weight::from_parts(57_789_709, 0)
			.saturating_add(Weight::from_parts(0, 3632))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::Accounts` (r:1 w:1)
	/// Proof: `OCEX::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 255]`.
	fn add_proxy_account(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `397`
		//  Estimated: `3862`
		// Minimum execution time: 69_812_000 picoseconds.
		Weight::from_parts(71_979_380, 0)
			.saturating_add(Weight::from_parts(0, 3862))
			// Standard Error: 45
			.saturating_add(Weight::from_parts(1_619, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::TradingPairs` (r:1 w:1)
	/// Proof: `OCEX::TradingPairs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 50000]`.
	fn close_trading_pair(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `3856`
		// Minimum execution time: 65_553_000 picoseconds.
		Weight::from_parts(67_539_432, 0)
			.saturating_add(Weight::from_parts(0, 3856))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::TradingPairs` (r:1 w:1)
	/// Proof: `OCEX::TradingPairs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 100000]`.
	fn open_trading_pair(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `3856`
		// Minimum execution time: 65_593_000 picoseconds.
		Weight::from_parts(67_481_003, 0)
			.saturating_add(Weight::from_parts(0, 3856))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::TradingPairs` (r:2 w:1)
	/// Proof: `OCEX::TradingPairs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 100000]`.
	fn register_trading_pair(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `6107`
		// Minimum execution time: 66_913_000 picoseconds.
		Weight::from_parts(68_752_355, 0)
			.saturating_add(Weight::from_parts(0, 6107))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(1, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::TradingPairs` (r:1 w:1)
	/// Proof: `OCEX::TradingPairs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 100000]`.
	fn update_trading_pair(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `420`
		//  Estimated: `3885`
		// Minimum execution time: 75_603_000 picoseconds.
		Weight::from_parts(77_960_257, 0)
			.saturating_add(Weight::from_parts(0, 3885))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(1, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::AllowlistedToken` (r:1 w:0)
	/// Proof: `OCEX::AllowlistedToken` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::Accounts` (r:1 w:0)
	/// Proof: `OCEX::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
	/// Storage: `OCEX::TotalAssets` (r:1 w:1)
	/// Proof: `OCEX::TotalAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 255]`.
	fn deposit(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `740`
		//  Estimated: `6232`
		// Minimum execution time: 173_106_000 picoseconds.
		Weight::from_parts(176_634_210, 0)
			.saturating_add(Weight::from_parts(0, 6232))
			// Standard Error: 79
			.saturating_add(Weight::from_parts(119, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::Accounts` (r:1 w:1)
	/// Proof: `OCEX::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 255]`.
	fn remove_proxy_account(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `429`
		//  Estimated: `3894`
		// Minimum execution time: 66_652_000 picoseconds.
		Weight::from_parts(68_834_613, 0)
			.saturating_add(Weight::from_parts(0, 3894))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OCEX::OnChainEvents` (r:1 w:1)
	/// Proof: `OCEX::OnChainEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::Withdrawals` (r:0 w:1)
	/// Proof: `OCEX::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::Snapshots` (r:0 w:1)
	/// Proof: `OCEX::Snapshots` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::FeesCollected` (r:0 w:1)
	/// Proof: `OCEX::FeesCollected` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::SnapshotNonce` (r:0 w:1)
	/// Proof: `OCEX::SnapshotNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn submit_snapshot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `193`
		//  Estimated: `1678`
		// Minimum execution time: 79_233_000 picoseconds.
		Weight::from_parts(80_253_000, 0)
			.saturating_add(Weight::from_parts(0, 1678))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `OCEX::FeesCollected` (r:1 w:1)
	/// Proof: `OCEX::FeesCollected` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 255]`.
	fn collect_fees(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3665`
		// Minimum execution time: 38_141_000 picoseconds.
		Weight::from_parts(39_738_014, 0)
			.saturating_add(Weight::from_parts(0, 3665))
			// Standard Error: 30
			.saturating_add(Weight::from_parts(170, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::ExchangeState` (r:0 w:1)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 100000]`.
	fn set_exchange_state(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3632`
		// Minimum execution time: 41_942_000 picoseconds.
		Weight::from_parts(43_427_631, 0)
			.saturating_add(Weight::from_parts(0, 3632))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `OCEX::ExchangeState` (r:1 w:0)
	/// Proof: `OCEX::ExchangeState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OCEX::IngressMessages` (r:1 w:1)
	/// Proof: `OCEX::IngressMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 255]`.
	fn set_balances(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `3612`
		// Minimum execution time: 26_691_000 picoseconds.
		Weight::from_parts(27_785_788, 0)
			.saturating_add(Weight::from_parts(0, 3612))
			// Standard Error: 24
			.saturating_add(Weight::from_parts(111, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `OCEX::Withdrawals` (r:1 w:1)
	/// Proof: `OCEX::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
	/// Storage: `OCEX::OnChainEvents` (r:1 w:1)
	/// Proof: `OCEX::OnChainEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 255]`.
	fn claim_withdraw(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `763`
		//  Estimated: `6232`
		// Minimum execution time: 157_716_000 picoseconds.
		Weight::from_parts(161_210_673, 0)
			.saturating_add(Weight::from_parts(0, 6232))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `OCEX::AllowlistedToken` (r:1 w:1)
	/// Proof: `OCEX::AllowlistedToken` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 65000]`.
	fn allowlist_token(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `1652`
		// Minimum execution time: 37_022_000 picoseconds.
		Weight::from_parts(38_478_293, 0)
			.saturating_add(Weight::from_parts(0, 1652))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `OCEX::AllowlistedToken` (r:1 w:1)
	/// Proof: `OCEX::AllowlistedToken` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[0, 65000]`.
	fn remove_allowlisted_token(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205`
		//  Estimated: `1690`
		// Minimum execution time: 40_312_000 picoseconds.
		Weight::from_parts(41_852_655, 0)
			.saturating_add(Weight::from_parts(0, 1690))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `OCEX::SnapshotNonce` (r:0 w:1)
	/// Proof: `OCEX::SnapshotNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_snapshot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_280_000 picoseconds.
		Weight::from_parts(12_800_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `OCEX::OrderbookOperatorPublicKey` (r:0 w:1)
	/// Proof: `OCEX::OrderbookOperatorPublicKey` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn whitelist_orderbook_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 27_741_000 picoseconds.
		Weight::from_parts(28_661_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
