
//! Autogenerated weights for `pallet_ocex_lmp`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-05, STEPS: `100`, REPEAT: 200, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Ubuntu-2204-jammy-amd64-base`, CPU: `Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./polkadex-node
// benchmark
// pallet
// --pallet
// pallet_ocex_lmp
// --steps
// 100
// --repeat
// 200
// --extrinsic
// *
// --output
// ocex_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_ocex_lmp`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> super::OcexWeightInfo for WeightInfo<T> {
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX Accounts (r:1 w:1)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `b` is `[0, 50000]`.
	fn register_main_account(_b: u32, ) -> Weight {
		(17_768_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX Accounts (r:1 w:1)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `x` is `[0, 255]`.
	fn add_proxy_account(_x: u32, ) -> Weight {
		(21_440_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX TradingPairs (r:1 w:1)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `x` is `[1, 50000]`.
	fn close_trading_pair(_x: u32, ) -> Weight {
		(20_328_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX TradingPairs (r:1 w:1)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `x` is `[0, 100000]`.
	fn open_trading_pair(_x: u32, ) -> Weight {
		(20_326_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX TradingPairs (r:2 w:1)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `x` is `[0, 100000]`.
	fn register_trading_pair(_x: u32, ) -> Weight {
		(20_658_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX TradingPairs (r:1 w:1)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `x` is `[0, 100000]`.
	fn update_trading_pair(_x: u32, ) -> Weight {
		(22_009_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX AllowlistedToken (r:1 w:0)
	// Storage: OCEX Accounts (r:1 w:0)
	// Storage: Assets Asset (r:1 w:1)
	// Storage: Assets Account (r:2 w:2)
	// Storage: System Account (r:1 w:1)
	// Storage: OCEX TotalAssets (r:1 w:1)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `x` is `[1, 255]`.
	fn deposit(_x: u32, ) -> Weight {
		(52_152_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(9 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX Accounts (r:1 w:1)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `x` is `[1, 255]`.
	fn remove_proxy_account(_x: u32, ) -> Weight {
		(20_694_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OCEX SnapshotNonce (r:1 w:1)
	// Storage: OCEX UnprocessedSnapshots (r:1 w:0)
	// Storage: OCEX Authorities (r:1 w:0)
	// Storage: OCEX OnChainEvents (r:1 w:1)
	// Storage: OCEX Withdrawals (r:0 w:1)
	// Storage: OCEX Snapshots (r:0 w:1)
	// Storage: OCEX PendingSnapshotFromPreviousSet (r:0 w:1)
	// Storage: OCEX FeesCollected (r:0 w:1)
	fn submit_snapshot() -> Weight {
		(194_578_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: OCEX FeesCollected (r:1 w:1)
	/// The range of component `x` is `[0, 255]`.
	fn collect_fees(_x: u32, ) -> Weight {
		(13_842_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OCEX IngressMessages (r:1 w:1)
	// Storage: OCEX ExchangeState (r:0 w:1)
	/// The range of component `x` is `[0, 100000]`.
	fn set_exchange_state(_x: u32, ) -> Weight {
		(12_813_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OCEX ExchangeState (r:1 w:0)
	// Storage: OCEX IngressMessages (r:1 w:1)
	/// The range of component `x` is `[0, 255]`.
	fn set_balances(_x: u32, ) -> Weight {
		(5_757_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OCEX Withdrawals (r:1 w:1)
	// Storage: Assets Asset (r:1 w:1)
	// Storage: Assets Account (r:2 w:2)
	// Storage: System Account (r:1 w:1)
	// Storage: OCEX OnChainEvents (r:1 w:1)
	/// The range of component `x` is `[1, 255]`.
	fn claim_withdraw(_x: u32, ) -> Weight {
		(47_489_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: OCEX AllowlistedToken (r:1 w:1)
	/// The range of component `x` is `[0, 65000]`.
	fn allowlist_token(_x: u32, ) -> Weight {
		(12_287_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OCEX AllowlistedToken (r:1 w:1)
	/// The range of component `x` is `[0, 65000]`.
	fn remove_allowlisted_token(_x: u32, ) -> Weight {
		(13_284_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OCEX SnapshotNonce (r:0 w:1)
	fn set_snapshot() -> Weight {
		(2_950_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OCEX PendingWithdrawalsAllowedPerSnapshot (r:0 w:1)
	fn change_pending_withdrawal_limit() -> Weight {
		(2_860_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OCEX SnapshotIntervalBlock (r:0 w:1)
	fn change_snapshot_interval_block() -> Weight {
		(2_857_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
