[package]
name = "rewards"
version = "1.0.0"
edition = "2021"
authors = ["Polkadex Authors"]
repository = 'https://github.com/Polkadex-Substrate/Polkadex/'
description = "A pallet that will give parachain rewards to participants"
license = "GPL-3.0-or-later"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, default-features = false }
log = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-support = { default-features = false, workspace = true }
frame-system = { default-features = false, workspace = true }
sp-runtime = { default-features = false, workspace = true }
sp-std = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
polkadex-primitives = { workspace = true, default-features = false }
rust_decimal = { workspace = true, features = ["scale-codec"], default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
pallet-timestamp = { workspace = true, default-features = false }
once_cell = { version = "1.17.0", default-features = false }

[dev-dependencies]
pallet-assets = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
sp-application-crypto = { workspace = true }
sp-keystore = { workspace = true }
frame-benchmarking = { workspace = true }
anyhow = { workspace = true }
sp-io = { workspace = true }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "log/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-core/std",
    "polkadex-primitives/std",
    "rust_decimal/std",
    "pallet-timestamp/std",
]
