[package]
name = "engine-rpc"
version = "0.1.0"
authors = ["Polkadex Team"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
serde = { version = "1.0.101", features = ["derive"], optional = true }
runtime-api = { package="engine-runtime-api", path = "../runtime-api" }
pallet-polkadex = { default-features = false, path = "../", package="polkadex-engine" }
sp-rpc = {git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false}
sp-runtime = {git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false}
sp-blockchain = {git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false}
sp-api = {git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false}
sp-arithmetic = {git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false}
sp-std = {git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false}
sp-core = {git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false}
