[package]
name = "ipfs-pallet"
authors = ["Gautham <gautham@polkadex.trade>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
offchain-ipfs-primitives = { path = "../../offchain-ipfs-primitives", default-features = false }
# Polkadex dependencies
polkadex-primitives = { git = "https://github.com/Polkadex-Substrate/polkadex-primitives.git", default-features = false, branch = 'gj-substrate-master' }
# ORML Pallets
codec = { version = "2.0.0", package = "parity-scale-codec", default-features = false, features = ["derive"] }
serde = { version = "1.0.126", optional = true }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
cid = {version="0.7.0", default-features = false, features = ["scale-codec"]}

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-core/std",
    "offchain-ipfs-primitives/std",
    "frame-support/std",
    "polkadex-primitives/std",
    "sp-inherents/std",
    "cid/std"
]