[package]
name = "pallet-asset-handler-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { workspace = true, default-features = false, features = ["derive"] }
serde = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
sp-rpc = { workspace = true, default-features = false }
sp-blockchain = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
polkadex-primitives = { workspace = true, defaull-features = false }
pallet-asset-handler-runtime-api = { path = "runtime-api" }
