[package]
name = "ocex-primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { version = "3.0.0", package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-api = {default-features = false, branch="polkadot-v0.9.19", git = 'https://github.com/paritytech/substrate'}
sp-application-crypto = {default-features = false, branch="polkadot-v0.9.19", git = 'https://github.com/paritytech/substrate'}
sp-core = {default-features = false, branch="polkadot-v0.9.19", git = 'https://github.com/paritytech/substrate'}
sp-runtime = {default-features = false, branch="polkadot-v0.9.19", git = 'https://github.com/paritytech/substrate'}
sp-std = {default-features = false, branch="polkadot-v0.9.19", git = 'https://github.com/paritytech/substrate'}
polkadex-primitives = { default-features = false, branch = "polkadot-v0.9.28", git = "https://github.com/Polkadex-Substrate/polkadex-primitives.git" }


[features]
default = ["std"]
std = [
    "codec/std",
    "sp-api/std",
    "sp-application-crypto/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "scale-info/std",
    "polkadex-primitives/std"
]