[package]
name = "lmp-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
orderbook-primitives = { git = "https://github.com/Polkadex-Substrate/Polkadex.git", branch = "mainnet-release" }
polkadex-primitives = { git = "https://github.com/Polkadex-Substrate/Polkadex.git", branch = "ksr/trading-reward" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
subxt = {git = "https://github.com/paritytech/subxt"}
subxt-signer = {git = "https://github.com/paritytech/subxt"}
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros", "time"] }
rust_decimal = { git = "https://github.com/Polkadex-Substrate/rust-decimal.git", branch = "master", default-features = false }
structopt = { version = "0.3" }
env_logger = "0.11.5"

[patch.'https://github.com/w3f/ring-vrf']
bandersnatch_vrfs = { git = "https://github.com/w3f//ring-vrf.git", rev = "0fef8266d851932ad25d6b41bc4b34d834d1e11d"}
