[package]
name = "bls-primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {version="0.4.17", optional=true}
substrate-bip39 = { version = "0.4.4", optional = true }
tiny-bip39 = { version = "0.8.2", optional = true }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
serde_json = {version = "1.0.94", optional = true}
blst = {version = "0.3.10", default-features = false, optional=true}
parity-scale-codec = { workspace = true, default-features = false, features = ["max-encoded-len"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
hex = {version="0.4.3", optional= true}

[features]
default = ["std"]
std = [
    "log",
    "hex",
    "serde_json",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-runtime-interface/std",
    "sp-application-crypto/std",
    "sp-core/full_crypto",
    "sp-std/std",
    "substrate-bip39",
    "tiny-bip39",
    "blst",
    ]