[package]
name = "thea-primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-api  = { workspace = true, default-features = false }
sp-std  = { workspace = true, default-features = false }
sp-runtime  = { workspace = true, default-features = false }
frame-support  = { workspace = true, default-features = false }
sp-application-crypto = {workspace = true, default-features = false}
sp-io = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
xcm = { workspace = true, default-features = false }
bls-primitives = {workspace= true, default-features = false}
polkadex-primitives = {workspace = true, default-features = false}
hex = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-runtime/std",
    "sp-api/std",
    "sp-std/std",
    "sp-application-crypto/std",
    "bls-primitives/std",
    "sp-io/std",
    "sp-core/std",
    "sp-std/std",
    "xcm/std",
    "sp-runtime/std",
    "polkadex-primitives/std",
    "hex/std"
]