[package]
name = "thea-primitives"
version = "1.1.0"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-api = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-runtime-interface = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
sp-application-crypto = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
xcm = { workspace = true, default-features = false }
polkadex-primitives = { workspace = true, default-features = false }
hex = { version = "0.4", default-features = false }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
frost-secp256k1 = {git ="https://github.com/Polkadex-Substrate/frost.git", branch = "ethereum", optional = true, features = ["serialization"]}
rand = { version = "0.8.5", optional = true }
log = "0.4.20"
binary-merkle-tree = { version = "12.0.0", default-features = false }


[features]
default = ["std"]
std = [
  "binary-merkle-tree/std",
  "log/std",
  "rand",
  "frost-secp256k1",
  "serde/std",
  "serde_json/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "sp-runtime/std",
  "sp-api/std",
  "sp-std/std",
  "sp-application-crypto/std",
  "sp-io/std",
  "sp-core/std",
  "sp-std/std",
  "xcm/std",
  "sp-runtime/std",
  "sp-runtime-interface/std",
  "polkadex-primitives/std",
  "hex/std",
]
