[package]
name = "thea-message-handler"
version = "1.1.0"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-support = { default-features = false, workspace = true }
frame-system = { default-features = false, workspace = true }
sp-runtime = { default-features = false, workspace = true }
sp-std = { workspace = true, default-features = false }
polkadex-primitives = { workspace = true, default-features = false }
pallet-timestamp = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
thea-primitives = { path = "../../primitives/thea", default-features = false }
lazy_static = { version = "1.4.0", default-features = false, features = ["spin_no_std"], optional = true }
log = { version = "0.4.19", default-features = false }

[dev-dependencies]
pallet-assets = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
sp-application-crypto = { workspace = true }
sp-keystore = { workspace = true }
thea = { path = "../thea" }
thea-executor = { path = "../thea-executor" }
hex = "0.4.3"
lazy_static = "1.4.0"

[features]
default = ["std"]
std = [
  "log/std",
  "sp-io/std",
  "sp-application-crypto/std",
  "thea-primitives/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
  "sp-runtime/std",
  "sp-std/std",
  "polkadex-primitives/std",
  "pallet-timestamp/std",
  "sp-core/std",
  "frame-benchmarking/std",
]
runtime-benchmarks = [
  "sp-runtime/runtime-benchmarks",
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "lazy_static",
]
try-runtime = ["frame-support/try-runtime"]
