[package]
name = "pallet-lmp"
version = "0.0.1"
authors = ["Gautham J <gautham@polkadex.trade>"]
edition = "2021"
license = "GNU GPL v3"
homepage = "https://polkadex.trade"
repository = "https://github.com/Polkadex-Substrate/Polkadex/"
description = "Polkadex Liquidity Mining pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.20"
parity-scale-codec = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-system = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
orderbook-primitives = { path = "../../primitives/orderbook", default-features = false }
polkadex-primitives = { path = "../../primitives/polkadex", default-features = false }
rust_decimal = { workspace = true, default-features = false }

[dev-dependencies]
pallet-ocex-lmp = { path = "../ocex", default-features = false }
pallet-assets = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
pallet-timestamp = { workspace = true, default-features = false }
sp-application-crypto = { workspace = true }
sp-io = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
  "log/std",
  "parity-scale-codec/std",
  "frame-system/std",
  "frame-support/std",
  "scale-info/std",
  "orderbook-primitives/std",
  "polkadex-primitives/std",
  "rust_decimal/std",
  "sp-runtime/std",
  "sp-std/std",
  "pallet-ocex-lmp/std",
  "pallet-assets/std",
  "pallet-balances/std",
  "pallet-timestamp/std",
  "sp-io/std",
  "sp-application-crypto/std",
  "sp-io/std",
]
