//! Autogenerated weights for `thea_message_handler`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-02-02, STEPS: `100`, REPEAT: `200`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-41-122`, CPU: `AMD EPYC 7571`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./polkadex-node
// benchmark
// pallet
// --pallet
// thea-message-handler
// --steps
// 100
// --repeat
// 200
// --extrinsic
// *
// --output
// ./weights/thea_message_handler_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `thea_message_handler`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `TheaMH::Authorities` (r:0 w:1)
	/// Proof: `TheaMH::Authorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TheaMH::ValidatorSetId` (r:0 w:1)
	/// Proof: `TheaMH::ValidatorSetId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[0, 4294967295]`.
	fn insert_authorities(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 19_840_000 picoseconds.
		Weight::from_parts(20_793_457, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TheaMH::ValidatorSetId` (r:1 w:0)
	/// Proof: `TheaMH::ValidatorSetId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TheaExecutor::Metadata` (r:1 w:0)
	/// Proof: `TheaExecutor::Metadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TheaMH::IncomingNonce` (r:0 w:1)
	/// Proof: `TheaMH::IncomingNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TheaMH::IncomingMessages` (r:0 w:1)
	/// Proof: `TheaMH::IncomingMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn incoming_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `82`
		//  Estimated: `3547`
		// Minimum execution time: 95_831_000 picoseconds.
		Weight::from_parts(97_451_000, 0)
			.saturating_add(Weight::from_parts(0, 3547))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TheaMH::IncomingNonce` (r:0 w:1)
	/// Proof: `TheaMH::IncomingNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[1, 4294967295]`.
	fn update_incoming_nonce(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 14_960_000 picoseconds.
		Weight::from_parts(15_638_456, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TheaMH::OutgoingNonce` (r:0 w:1)
	/// Proof: `TheaMH::OutgoingNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[1, 4294967295]`.
	fn update_outgoing_nonce(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 14_740_000 picoseconds.
		Weight::from_parts(15_625_467, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TheaMH::ValidatorSetId` (r:1 w:0)
	/// Proof: `TheaMH::ValidatorSetId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TheaMH::Authorities` (r:1 w:0)
	/// Proof: `TheaMH::Authorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TheaMH::OutgoingNonce` (r:1 w:1)
	/// Proof: `TheaMH::OutgoingNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TheaMH::OutgoingMessages` (r:0 w:1)
	/// Proof: `TheaMH::OutgoingMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn send_thea_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `172`
		//  Estimated: `3637`
		// Minimum execution time: 41_120_000 picoseconds.
		Weight::from_parts(42_110_000, 0)
			.saturating_add(Weight::from_parts(0, 3637))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
