// This file is part of Polkadex.
//
// Copyright (c) 2023 Polkadex oü.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `thea_message_handler`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-15, STEPS: `100`, REPEAT: `200`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ubuntu-2204-jammy-amd64-base`, CPU: `Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./polkadex-node
// benchmark
// pallet
// --pallet
// thea-message-handler
// --steps
// 100
// --repeat
// 200
// --extrinsic
// *
// --output
// liquidity_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `thea_message_handler`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: TheaMH Authorities (r:0 w:1)
	/// Proof Skipped: TheaMH Authorities (max_values: None, max_size: None, mode: Measured)
	/// Storage: TheaMH ValidatorSetId (r:0 w:1)
	/// Proof Skipped: TheaMH ValidatorSetId (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `b` is `[0, 4294967295]`.
	fn insert_authorities(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_557_000 picoseconds.
		Weight::from_parts(5_048_603, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: TheaMH IncomingNonce (r:1 w:1)
	/// Proof Skipped: TheaMH IncomingNonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: TheaMH ValidatorSetId (r:1 w:0)
	/// Proof Skipped: TheaMH ValidatorSetId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: TheaMH IncomingMessages (r:0 w:1)
	/// Proof Skipped: TheaMH IncomingMessages (max_values: None, max_size: None, mode: Measured)
	fn incoming_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `1593`
		// Minimum execution time: 28_319_000 picoseconds.
		Weight::from_parts(36_715_000, 0)
			.saturating_add(Weight::from_parts(0, 1593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: TheaMH IncomingNonce (r:1 w:1)
	/// Proof Skipped: TheaMH IncomingNonce (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `b` is `[1, 4294967295]`.
	fn update_incoming_nonce(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1561`
		// Minimum execution time: 5_647_000 picoseconds.
		Weight::from_parts(6_126_151, 0)
			.saturating_add(Weight::from_parts(0, 1561))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
