
//! Autogenerated weights for `orml_tokens`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-09-12, STEPS: `20`, REPEAT: 50, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/polkadex-node
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet=orml_tokens
// --extrinsic=*
// --steps
// 20
// --repeat
// 50
// --output=benchout/orml_tokens.rs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for orml_tokens.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> orml_tokens::WeightInfo for WeightInfo<T> {
	fn batch(c: u32, ) -> Weight {
		(243_172_000 as Weight)
			// Standard Error: 20_000
			.saturating_add((5_448_000 as Weight).saturating_mul(c as Weight))
	}
	fn as_derivative() -> Weight {
		(3_516_000 as Weight)
	}
	fn batch_all(c: u32, ) -> Weight {
		(98_788_000 as Weight)
			// Standard Error: 21_000
			.saturating_add((5_764_000 as Weight).saturating_mul(c as Weight))
	}
}
