FROM ubuntu:22.04 As builder

ARG branch=mainnet-release

  

RUN apt-get update && apt-get install --assume-yes git curl build-essential cmake clang jq
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
  export PATH="$PATH:$HOME/.cargo/bin" && \
  rustup install 1.67 --no-self-update && \
  rustup toolchain install nightly-2023-01-01 --no-self-update && \
  rustup target add wasm32-unknown-unknown --toolchain nightly-2023-01-01 && \
  rustup default nightly-2023-01-01 && \
  git clone https://github.com/Polkadex-Substrate/Polkadex  && \
  cd Polkadex && \ 
  git checkout $branch && \
  cargo  +nightly-2023-01-01 build --release


FROM ubuntu:22.04

RUN mkdir /data && mkdir /data/bootnode && mkdir /data/validator

COPY --from=builder /Polkadex/target/release/polkadex-node /data
COPY --from=builder /Polkadex/extras/customSpecRaw.json /data

VOLUME ["/data"]

EXPOSE 10000 9068 10001 9069 10002 9070 30333 9944 9933
ENTRYPOINT ["/data/polkadex-node"]
