[package]
authors = ['Polkadex Team <https://github.com/Polkadex-Substrate/Polkadex']
description = 'Polkadex: Orderbook based Trading Chain Node.'
edition = '2018'
homepage = 'https://github.com/Polkadex-Substrate/Polkadex'
license = 'Unlicense'
name = 'polkadex-engine'
repository = 'https://github.com/Polkadex-Substrate/Polkadex'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dev-dependencies]
serde_json = "1.0.41"

[dependencies]
compare = "0.1.0"
serde = { version = "1.0.101", default-features = false, features = ["derive"], optional = true }
jsonrpc-core = "14.0.3"
hex = { version = "0.4.2", default-features = false }
polkadex-custom-assets = { path = "../polkadex-custom-assets", default-features = false }
polkadex-swap-engine = { path = "../polkadex-uniswap", default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false }
sp-arithmetic = { git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false }
frame-support = { git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate.git', branch = "master", default-features = false }
pallet-idenity = {default-features = false, path = "../polkadex-identity-pallet"}

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'polkadex-swap-engine/std',
    'sp-io/std',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'sp-std/std',
    'polkadex-custom-assets/std',
    'sp-core/std',
    'pallet-idenity/std'
]
