[package]
name = "check-off-on-deviation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
jsonrpsee = {version = "0.20.1", features = ["client","macros"]}
orderbook-primitives = { version = "1.1.0", path = "../../primitives/orderbook" }
tokio = { version = "1.27", features = ["rt-multi-thread", "macros", "time"] }
