[package]
name = "bls-primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true, optional = true }
substrate-bip39 = { version = "0.4.4", optional = true }
tiny-bip39 = { version = "1.0.0", optional = true }
sp-runtime-interface = { workspace = true, default-features = false }
sp-application-crypto = { workspace = true, default-features = false }
sp-keystore = { workspace = true, default-features = false }
sp-externalities = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
serde_json = { workspace = true, optional = true }
blst = { version = "0.3.10", default-features = false, optional = true }
parity-scale-codec = { workspace = true, default-features = false, features = ["max-encoded-len"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
hex = {workspace = true, optional = true }

# Ark works
ark-bls12-381 = {version="0.4.0", default-features = false, features = ["curve"]}
ark-ec = {version="0.4.2", default-features = false}
ark-ff = {version="0.4.2", default-features = false}
ark-serialize = {version="0.4.2", default-features = false}
sha2 = {version="0.10.6", default-features = false}

[features]
default = ["std"]
std = [
    "sha2/std",
    "ark-bls12-381/std",
    "ark-ec/std",
    "ark-ff/std",
    "ark-serialize/std",
    "log",
    "hex",
    "serde_json",
    "parity-scale-codec/std",
    "sp-application-crypto/std",
    "sp-keystore/std",
    "sp-externalities/std",
    "scale-info/std",
    "sp-runtime-interface/std",
    "sp-core/full_crypto",
    "sp-core/std",
    "sp-std/std",
    "substrate-bip39",
    "tiny-bip39",
    "blst",
]
