name: TestnetEKSDeployment
on:
  push:
    branches: [redux-cicd,eks-deploy]

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0a409f54f89b4a989
          ec2-instance-type: c5.2xlarge
          subnet-id: subnet-a4d326e8
          security-group-id: sg-078363c0f7b5f0b41
          iam-role-name: github-runner-role 
          aws-resource-tags: > 
            [
              {"Key": "Name", "Value": "github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]
  buildbinary:
    needs: start-runner 
    name: Build Binary
    runs-on: ${{ needs.start-runner.outputs.label }} 
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: |
            export PATH=/home/ubuntu/.cargo/bin/:$PATH
            echo $PATH
            ./scripts/init.sh
            cargo build --release 
            ./target/release/polkadex-node build-spec --disable-default-bootnode --chain udon > customSpec.json
            ./target/release/polkadex-node build-spec --chain=customSpec.json --raw --disable-default-bootnode > customSpecRaw.json
      - name: PackRelease
        run: |
           zip polkadex.zip --junk-paths target/release/polkadex-node  customSpecRaw.json 
      - name: Upload to S3
        run: |   
          aws s3 cp polkadex.zip s3://polkadex-fullnode/testnet/public/binary/${{ github.sha }}/
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner 
      - buildbinary
      #- updatek8smanifests
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}          
