node-mainnet:
  - node/mainnet/*

node-testnet:
  - node/testnet/*

runtime-mainnet:
  - runtime/mainnet/*

runtime-testnet:
  - runtime/testnet/*

pallet-engine-old:
  - pallets/polkadex/*

pallet-custom-assets:
  - pallets/polkadex-custom-assets/*
pallet-identity:
  - pallets/polkadex-identity-pallet/*
pallet-uniswap:
  - pallets/polkadex-uniswap/*
pallet-engine:
  - pallets/polkadex-engine/*